Test if ruby script works

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,85 +1,86 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ruby
 
-set -e # bail if any command fails
-#set -x # debug
+require 'date'
+require 'net/http'
 
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
+# Exit if any command fails
+def exit_on_failure
+  yield
+rescue => e
+  puts e.message
+  exit 1
+end
 
-if [ ! -f "$ENV_DIR/MAXMIND_KEY" ]; then
-	echo "-----> You must define the environment variable MAXMIND_KEY with your license key."
+build_dir = ARGV[0]
+cache_dir = ARGV[1]
+env_dir = ARGV[2]
 
-	exit 1
-fi
+maxmind_key_path = File.join(env_dir, 'MAXMIND_KEY')
+unless File.exist?(maxmind_key_path)
+  puts '-----> You must define the environment variable MAXMIND_KEY with your license key.'
+  exit 1
+end
 
-MAXMIND_KEY=`cat $ENV_DIR/MAXMIND_KEY`
-MAXMIND_EDITIONS=`cat $ENV_DIR/MAXMIND_EDITIONS`
+maxmind_key = File.read(maxmind_key_path).strip
+maxmind_editions = File.read(File.join(env_dir, 'MAXMIND_EDITIONS')).strip
 
-mkdir -p $CACHE_DIR
+Dir.mkdir(cache_dir) unless Dir.exist?(cache_dir)
 
-download(){
-	EDITION=$1
+# def download(edition, maxmind_key, cache_dir, build_dir)
+#   url = "https://download.maxmind.com/app/geoip_download?edition_id=#{edition}&suffix=tar.gz&license_key=#{maxmind_key}"
+#   tar = File.join(cache_dir, "#{edition}.tar.gz")
+#   tar_new = File.join(cache_dir, "#{edition}-new.tar.gz")
+#   db = File.join(cache_dir, "#{edition}.mmdb")
 
-  URL="https://download.maxmind.com/app/geoip_download?edition_id=${EDITION}&suffix=tar.gz&license_key=$MAXMIND_KEY"
-	TAR="$CACHE_DIR/$EDITION.tar.gz"
-	TAR_NEW="$CACHE_DIR/$EDITION-new.tar.gz"
-	DB="$CACHE_DIR/$EDITION.mmdb"
+#   newer_version = false
 
-	if [ -f $TAR ]; then
-    response=$(curl --silent --head $URL | tee \
-                      >(awk '/HTTP\/2 /{print $0}') \
-                      >(awk '/^[Ll]ast-[Mm]odified/{print $0}') \
-                      > /dev/null )
-    code=$(echo "$response" | grep 'HTTP\/2' | sed 's/^HTTP\/2 //')
-    if [[ "$code" != *"200"* ]]; then
-      echo "WARNING $EDITION: Unable to reach Maxmind, received: $code"
-      newer_version=false
-    else
-      modified=$(echo "$response" | grep '[Ll]ast-[Mm]odified' |  sed 's/^[Ll]ast-[Mm]odified: //')
-      echo "-----> $EDITION: modified $modified"
-      remote_ctime=$(date --date="$modified" +%s)
-      local_ctime=$(stat -c %y "$TAR")
-      local_ctime=$(date --date="$local_ctime" +%s)
-      if [ $local_ctime -lt $remote_ctime ]; then
-        newer_version=true
-      fi
-    fi
-  fi
+#   if File.exist?(tar)
+#     uri = URI(url)
+#     response = Net::HTTP.get_response(uri)
 
-  if [ ! -f $TAR ] || [ $newer_version ]; then
-    if [ $newer_version ]; then
-      echo "-----> $EDITION: Found newer version of the TAR file on the server, downloading."
-    else
-      echo "-----> $EDITION: Database does not exist in cache, downloading."
-    fi
+#     if response.code != '200'
+#       puts "WARNING #{edition}: Unable to reach Maxmind, received: #{response.code}"
+#     else
+#       modified = response['last-modified']
+#       puts "-----> #{edition}: modified #{modified}"
+#       remote_ctime = DateTime.parse(modified).to_time.to_i
+#       local_ctime = File.mtime(tar).to_i
 
-    curl -o $TAR_NEW -L $URL
-  else
-    echo "-----> $EDITION: Database already exists in cache and it's up to date."
-    TAR_NEW=$TAR
-  fi
+#       newer_version = local_ctime < remote_ctime
+#     end
+#   end
 
-  echo "-----> $EDITION: Extracting $TAR_NEW"
-  tar -zxvf $TAR_NEW -C $CACHE_DIR --no-anchored --strip-components=1 "$EDITION.mmdb"
-  if [ $? -ne 0 ]; then
-    if [ $newer_version ]; then
-      echo "-----> WARNING $EDITION: Could not download TAR file! Using old cached version."
-    else
-      echo "-----> ERROR $EDITION: Could not download TAR file! Cannot continue!!!"
-      exit 1
-    fi
-  fi
+#   if !File.exist?(tar) || newer_version
+#     puts "-----> #{edition}: #{newer_version ? 'Found newer version of the TAR file on the server, downloading.' : 'Database does not exist in cache, downloading.'}"
+#     File.write(tar_new, Net::HTTP.get(URI(url)))
+#   else
+#     puts "-----> #{edition}: Database already exists in cache and it's up to date."
+#     tar_new = tar
+#   end
 
-	OUTPUT="$BUILD_DIR/$SAVE"
-	echo "-----> $EDITION: Moving $DB to $OUTPUT"
-	mv $DB $OUTPUT
-	mv $TAR_NEW $TAR || true
-}
+#   puts "-----> #{edition}: Extracting #{tar_new}"
+#   system("tar -zxvf #{tar_new} -C #{cache_dir} --no-anchored --strip-components=1 #{edition}.mmdb")
 
-IFS=', ' read -a editions <<< "$MAXMIND_EDITIONS"
+#   if $?.exitstatus != 0
+#     if newer_version
+#       puts "-----> WARNING #{edition}: Could not download TAR file! Using old cached version."
+#     else
+#       puts "-----> ERROR #{edition}: Could not download TAR file! Cannot continue!!!"
+#       exit 1
+#     end
+#   end
 
-for edition in "${editions[@]}"
-do
-    download "$edition"
-done
+#   output = File.join(build_dir, edition)
+#   puts "-----> #{edition}: Moving #{db} to #{output}"
+#   File.rename(db, output)
+#   File.rename(tar_new, tar) rescue nil
+# end
+
+editions = maxmind_editions.split(', ')
+
+editions.each do |edition|
+  exit_on_failure do
+    # download(edition, maxmind_key, cache_dir, build_dir)
+    puts "-----> #{edition}: Downloading #{edition}"
+  end
+end
